// AUTO-GENERATED FILE
// Generated by: scripts/generate-mfe-manifests.ts
// Do not edit manually!
// Regenerate: npm run generate:mfe-manifests

import mfe0 from '@/mfe_packages/demo-mfe/mfe.json';

export const MFE_MANIFESTS = [
  mfe0,
];

// Get all MFE manifests
// Allows Vite to statically analyze imports without warnings
export function getMfeManifests() {
  return MFE_MANIFESTS;
}
